#######################################################################
#
# GENERAL CONFIGURATION
#
#######################################################################
[population]
    num_generations = 20
    size_population = 40
    prob_mutation = 0.3
    pressure = 0.25
    optimisation = 'minimise'
    crossover = 'different_points'
    mutation = 'normal'
    num_genes = 5
    min_values = 0.0
    max_values = 0.1
    
    [population.fitness_function]
        epidemicModel = 'SEIR'
        initialStates = [2999971.0, 0.0, 29.0, 0.0, 0.0]
        period = 29.0
        step = 1
